[tool.ruff]
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "C",     # flake8-comprehensions
    "B",     # flake8-bugbear
    "ASYNC", # flake8-async
    "C4",    # flake8-comprehensions
    "G",     # flake8-logging-format
    "PL",     # pylint
]
ignore = [
    "E501",     # line too long, handled by black
    "PLR1711",  # useless `return` statement at end of function
    "PLC1901",  # compare-to-empty-string
    "B904",     # raise without from inside except
]
line-length = 100

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*.py" = ["PL"]

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | sdist
    | venv
    | env
    | \.env
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
skip_gitignore = true
skip = ".bzr,.direnv,.eggs,.git,.hg,.mypy_cache,.nox,.pants.d,.svn,.tox,.venv,_build,buck-out,build,dist,node_modules,venv,migrations,urls.py"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"