name: build

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build with Tox
        run: |
          tox -e bundle

      - name: Upload PEX file
        uses: actions/upload-artifact@v3
        with:
          name: sonic-salt-deployer-${{ matrix.python-version }}
          path: dist/sonic-salt-deployer
